### ISSUE TITLE
Failed to load dynamic library on encrytion

### ISSUE THREAD

**Issue by KaungZawHtet** [simolus3/sqlite3.dart#10]
Everything is fine on using non-encrypted sqlite by FlutterQueryExecutor. When switch to encrypted version by EncryptedExecutor, exception is shown.

Err:
`Failed to load dynamic library (dlopen failed: library ".../lib/libsqlite3.so" not found)`

Here is my code

```
class MyDatabase extends _$MyDatabase {
  MyDatabase()

      : super((EncryptedExecutor.inDatabaseFolder(
        password: "mypw",
    path: 'db.sqlite3',
     singleInstance: true, 
   
    logStatements: true,
     creator: (file) async { 
     final content = await rootBundle.load(join("assets/data", "db.sqlite3")); 
     await file.writeAsBytes(content.buffer.asUint8List()); 
     
   }, 
  )
  ));
...
```

my dependency for encryption:
```
  moor: 
  encrypted_moor:
   git:
    url: https://github.com/simolus3/moor.git
    path: extras/encryption 
```
