### ISSUE TITLE
Windows application build fails - unreferenced local variable in file sqlite3.c

### ISSUE THREAD

**Issue by Alecia1997** [simolus3/sqlite3.dart#122]
My windows build is failing. I'm receiving the following error: 

Nuget.exe not found, trying to download or use cached version
root/project/build/windows/_deps/sqlite3-src/sqlite3.c(114582,7): warning c4101: 'rc': unreferenced local variable

**Comment by simolus3** [comment]
Is the build really failing because of this? I'm aware of the compiler warning, but the build shouldn't fail due to this.

Did you customize your `CMakeLists.txt` on Windows?

**Comment by simolus3** [comment]
Out of interest, does this still happen on `main`? If you could test this by running a clean build after adding this to your pubspec, it would help a lot:

```yaml
dependency_overrides:
  sqlite3_flutter_libs:
    git:
      url: https://github.com/simolus3/sqlite3.dart.git
      ref: main
      path: sqlite3_flutter_libs
```

I think I've fixed this in 43ea86d495f99bf6103f92d0e1cd27c86612faab and I'll include that change in the next release if it works for you.
