### ISSUE TITLE
Error (Xcode): Framework 'SQLCipher' not found in iOS

### ISSUE THREAD

**Issue by alexjane19** [simolus3/sqlite3.dart#229]
I encountered a peculiar issue. Previously, my iOS project functioned properly, and I could run it without any trouble. However, after updating Xcode, I encountered the error: `Error (Xcode): Framework 'SQLCipher' not found.`

Interestingly, this configuration operates seamlessly on MacOS, allowing me to run my Flutter app without any issues.

Error:
```
Failed to build iOS app
Could not build the precompiled application for the device.
Error (Xcode): Framework 'SQLCipher' not found

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

```

My Flutter info:

```
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.4.1 23E224 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
```

pubspec.yaml:

```
environment:
  sdk: ">=3.0.0 <3.16.5"

dependencies:
  animated_text_kit: ^4.2.2
  app_tracking_transparency: ^2.0.4
  bloc: ^8.1.1
  connectivity_plus: ^5.0.2
  countries_utils: ^1.0.1
  country_icons: ^3.0.0
  desktop_window: ^0.4.0
  device_info_plus: ^9.1.1
  dio: ^5.4.0
  drift: ^2.14.1
  drift_db_viewer: ^2.0.0
  encrypt: ^5.0.3
  ffi: ^2.1.0
  firebase_analytics: ^10.8.0
  firebase_core: ^2.24.2
  firebase_database: ^10.4.0
  firebase_in_app_messaging: ^0.7.4+8
  firebase_messaging: ^14.7.10
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^16.3.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  flutter_slidable: ^3.0.1
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.6.0
  freezed: ^2.4.6
  get_time_ago: ^1.3.1
  google_fonts: ^6.1.0
  google_mobile_ads: ^4.0.0
  in_app_review: ^2.0.8
  installed_apps: ^1.4.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logging: ^1.2.0
  mutex: ^3.1.0
  network_info_plus: ^4.1.0
  package_info_plus: ^5.0.1
  path: ^1.8.3
  path_provider: ^2.1.1
  proxy_manager: ^0.0.3
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  riverpod_navigator: ^1.0.10
  rxdart: ^0.27.7
  sentry_flutter: ^7.14.0
  share_plus: ^7.2.2
  shared_preferences: ^2.2.2
  showcaseview: ^2.0.3
  simple_ripple_animation: ^0.0.9
  socks5_proxy: ^1.0.4
  sqlcipher_flutter_libs: ^0.6.0
  sqlite3: ^2.3.0
  url_launcher: ^6.2.2
  uuid: ^4.2.2

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  drift_dev: ^2.14.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.2
  msix: ^3.16.7
  very_good_analysis: ^5.1.0
```

project.pbxproj:

```
.
.
.
		OTHER_LDFLAGS = (
					"-framework",
					SQLCipher,
				);
.
.
.

```

 pod --version
1.14.3

$ pod install
```
Analyzing dependencies
firebase_analytics: Using Firebase SDK version '10.18.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '10.18.0' defined in 'firebase_core'
firebase_database: Using Firebase SDK version '10.18.0' defined in 'firebase_core'
firebase_in_app_messaging: Using Firebase SDK version '10.18.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '10.18.0' defined in 'firebase_core'
Downloading dependencies
Installing Firebase (10.18.0)
Installing FirebaseABTesting (10.25.0)
Installing FirebaseAnalytics (10.18.0)
Installing FirebaseAppCheckInterop (10.25.0)
Installing FirebaseCore (10.18.0)
Installing FirebaseCoreInternal (10.25.0)
Installing FirebaseDatabase (10.18.0)
Installing FirebaseInAppMessaging (10.18.0-beta)
Installing FirebaseInstallations (10.25.0)
Installing FirebaseMessaging (10.18.0)
Installing FirebaseSharedSwift (10.25.0)
Installing Flutter (1.0.0)
Installing Google-Mobile-Ads-SDK (10.11.0)
Installing GoogleAppMeasurement (10.18.0)
Installing GoogleDataTransport (9.4.1)
Installing GoogleUserMessagingPlatform (2.4.0)
Installing GoogleUtilities (7.13.2)
Installing MTBBarcodeScanner (5.0.11)
Installing PromisesObjC (2.4.0)
Installing ReachabilitySwift (5.2.2)
Installing SQLCipher (4.5.7)
Installing Sentry (8.17.2)
Installing SentryPrivate (8.17.2)
Installing app_tracking_transparency (0.0.1)
Installing connectivity_plus (0.0.1)
Installing device_info_plus (0.0.1)
Installing firebase_analytics (10.8.0)
Installing firebase_core (2.24.2)
Installing firebase_database (10.4.0)
Installing firebase_in_app_messaging (0.7.4-8)
Installing firebase_messaging (14.7.10)
Installing flutter_local_notifications (0.0.1)
Installing google_mobile_ads (1.0.0)
Installing in_app_review (0.2.0)
Installing leveldb-library (1.22.5)
Installing nanopb (2.30909.1)
Installing network_info_plus (0.0.1)
Installing package_info_plus (0.4.5)
Installing path_provider_foundation (0.0.1)
Installing qr_code_scanner (0.2.0)
Installing sentry_flutter (0.0.1)
Installing share_plus (0.0.1)
Installing shared_preferences_foundation (0.0.1)
Installing sqlcipher_flutter_libs (0.0.1)
Installing url_launcher_ios (0.0.1)
Installing webview_flutter_wkwebview (0.0.1)
Generating Pods project
Integrating client project
Pod installation complete! There are 22 dependencies from the Podfile and 46 total pods installed.
```
