### ISSUE TITLE
Swift Compiler Error (Xcode): Main actor-isolated property 'systemVersion' can not be referenced from a nonisolated context

### ISSUE THREAD

**Issue by FayozbekJumabekov** [simolus3/sqlite3.dart#288]
![Image](https://github.com/user-attachments/assets/8098c474-bd33-4c6e-959f-9b731710142a)

here my related packages which i use:
drift: ^2.24.0
sqlcipher_flutter_libs: ^0.6.4
sqlite3: ^2.7.2

**Comment by FayozbekJumabekov** [comment]
>   drift: ^2.24.0
  sqlcipher_flutter_libs: ^0.6.4
  sqlite3: ^2.7.2

**Comment by FayozbekJumabekov** [comment]
> ![Image](https://github.com/user-attachments/assets/8098c474-bd33-4c6e-959f-9b731710142a)

here my related packages:   
 drift: ^2.24.0
 sqlcipher_flutter_libs: ^0.6.4
 sqlite3: ^2.7.2

**Comment by simolus3** [comment]
Thanks for the report! I've fixed this issue in 203220e424d3d63ad66c1bd831e39ae6d2b83460 and I'll release it soon.

You can add a dependency override to your pubspec to try it out in the meantime:

```yaml
dependency_overrides:
  sqlcipher_flutter_libs:
    git:
      url: git@github.com:simolus3/sqlite3.dart.git
      path: sqlcipher_flutter_libs 
```
